name: Flutter Web Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # - name: Analyze project source
        # run: dart analyze

      - name: Run tests
        run: flutter test

      - name: Build web
        run: flutter build web --web-renderer canvaskit --base-href "/flutter/calibration_reader/"

      - name: Upload Web Build Files
        uses: actions/upload-artifact@v4
        with:
          name: calibration_reader_web
          path: ./build/web
